Add Python 3 compatibility regarding __getitem__
Since `__getslice__` is deprecated since Python 3, slices now call `__getitem__` directly.  However, this has led to an AttributeError in `__getitem__`, as `'list' object has no attribute 'keys'`.  This should maintain backwards compatibility whilst fixing Python 3 support.