Fix indbmigrator problems (#644)
Fixes a problem with things being quoted twice due to them being quoted in the query then by the adapters in executesql where the placeholders also get quoted causing an error like this one:

    SyntaxError: syntax error at or near "applications"
    LINE 1: ...RT INTO web2py_filesystem(path,content) VALUES (''applicatio...

Fixes a py3 problem where you would have

        i = self.data.find("\n", self.p) + 1
    TypeError: argument should be integer or bytes-like object, not 'str'