Fixes to oracle.py
Fixes for the following errors:

>>> from gluon.dal import DAL
>>> db=DAL('oracle://***/***@****:1521/***',auto_import=True, db_codec='latin-1')

Traceback (most recent call last):
  File "*****/web2py/gluon/packages/dal/pydal/base.py", line 507, in __init__
    self._adapter = adapter(**kwargs)
  File "****/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 41, in __call__
    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)
  File "****/web2py/gluon/packages/dal/pydal/adapters/base.py", line 424, in __init__
    super(SQLAdapter, self).__init__(*args, **kwargs)
  File "*****/web2py/gluon/packages/dal/pydal/adapters/base.py", line 86, in __init__
    self._initialize_()
TypeError: _initialize_() missing 1 required positional argument: 'do_connect'


>>> row = db.executesql(sql, as_dict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/****/web2py/gluon/packages/dal/pydal/base.py", line 878, in executesql
    adapter.execute(query)
  File "/****/web2py/gluon/packages/dal/pydal/adapters/__init__.py", line 69, in wrap
    return f(*args, **kwargs)
  File "/****/web2py/gluon/packages/dal/pydal/adapters/oracle.py", line 51, in execute
    i = 1
AttributeError: 'Oracle' object has no attribute 'REGEX_CLOB'